#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  2 12:29:51 2020

@author: madeleinericher
"""


from MaddyPN import PetriNet 
from MaddyPN import PetriNetModel

if __name__ == "__main__":
        #only runs this chunk of code if running the file directly, not as an import

    
        # Initialize an empty Petri net
    pn = PetriNet(number_of_runs=10)
    
    pn.plot_time_evolution()


### Abeta Pathology 
def add_abeta_pathology(PetriNet):
    
    #Places
    pn.add_place(initial_tokens=1, place_id="p_asec", label="alpha secretase")
    pn.add_place(1, place_id="p_APP_PM", label="APP at plasma membrane")
    pn.add_place(0, place_id="p_APP_endo", label="endocytosed APP")
    pn.add_place(0, place_id="p_sAPPa", label="soluble sAPP alpha")
    pn.add_place(0, place_id="p_CTF83", label="CTF83")
    pn.add_place(1, place_id="p_bsec", label="beta secretase")
    pn.add_place(0, place_id="p_sAPPb", label="soluble sAPP beta")
    pn.add_place(0, place_id="p_CTF99", label="CTF99")
    pn.add_place(0, place_id="p_AB", label="Amyloid beta peptide")
    pn.add_place(0, place_id="p_AICD", label="AICD")
    pn.add_place(1, place_id="p_gsec", label="gamma secretase")
    
    
    #Transitions
    pn.add_transition(transition_id = 't_asec_exp',
                   label                = "alpha secretase expression",
                   input_place_ids       = [],
                   input_arc_weights  = [], 
                   output_place_ids       = ['p_asec'],
                   output_arc_weights = [1])
   
    pn.add_transition(transition_id = 't_asec_deg',
                label      =     "alpha secretase degradation",
                input_place_ids         =  ['p_asec'],
                input_arc_weights  =  [1],
                output_place_ids         =  [],
                output_arc_weights =  [])
   
    pn.add_transition(transition_id = 't_APP_asec_cleav',
                   label      =     "APP cleavage by alpha secretase",
                   input_place_ids         =  ['p_APP_PM'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  ['p_sAPPa', 'p_CTF83'],
                   output_arc_weights =  [1, 1],
                   catal_place_ids = ["p_asec"],
                   catal_arc_weights = [1]) 
           
    pn.add_transition(transition_id = 't_APP_endo',
                   label      =     "APP endocytosis",
                   input_place_ids         =  ['p_APP_PM'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  ['p_APP_endo'],
                   output_arc_weights =  [1])
               
    pn.add_transition(transition_id = 't_APP_endo_bsec_cleav',
                   label      =     "APP cleavage by beta secretase",
                   input_place_ids         =  ['p_APP_endo'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  ['p_sAPPb', 'p_CTF99'],
                   output_arc_weights =  [1, 1],
                   catal_place_ids = ['p_bsec'],
                   catal_arc_weights= [1])
   
   
    pn.add_transition(transition_id = 't_bsec_exp',
                   label      =     "beta secretase expression",
                   input_place_ids         =  [],
                   input_arc_weights  =  [],
                   output_place_ids         =  ['p_bsec'],
                   output_arc_weights =  [1])
       
    pn.add_transition(transition_id = 't_bsec_deg',
                   label      =     "beta secretase degradation",
                   input_place_ids         =  ['p_bsec'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  [],
                   output_arc_weights =  [])
       
    pn.add_transition(transition_id = 't_CTF99_gsec_cleav',
                   label      =     "CTF99 cleavage by gamma secretase",
                   input_place_ids         =  ['p_CTF99'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  ['p_AB', 'p_AICD'],
                   output_arc_weights =  [1, 1],
                   catal_place_ids = ["p_gsec"],
                   catal_arc_weights = [1])
       
    pn.add_transition(transition_id = 't_gsec_exp',
                   label      =     "gamma secretase expression",
                   input_place_ids         =  [],
                   input_arc_weights  =  [],
                   output_place_ids         =  ['p_gsec'],
                   output_arc_weights =  [1])
       
    pn.add_transition(transition_id = 't_gsec_deg',
                   label      =     "gamma secretase degradation",
                   input_place_ids         =  ['p_gsec'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  [],
                   output_arc_weights =  [])
       
    pn.add_transition(transition_id = 't_bsec_deg',
                   label      =     "beta secretase degradation",
                   input_place_ids         =  ['p_bsec'],
                   input_arc_weights  =  [1],
                   output_place_ids         =  [],
                   output_arc_weights =  [])
    
    
    
    
    
    
    
    
    
    
    